language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./configure && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autotools-dev pkg-config libxfixes-dev libxmu-dev x11proto-xext-dev
