.\"
.\" Copyright © 2010 Kai-Uwe Behrmann, member of the OpenICC Project
.\"
.\" Permission to use, copy, modify, distribute, and sell this software and its
.\" documentation for any purpose is hereby granted without fee, provided that
.\" the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation, and that the name of Keith Packard not be used in
.\" advertising or publicity pertaining to distribution of the software without
.\" specific, written prior permission.  Keith Packard makes no
.\" representations about the suitability of this software for any purpose.  It
.\" is provided "as is" without express or implied warranty.
.\"
.\" KEITH PACKARD DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
.\" EVENT SHALL KEITH PACKARD BE LIABLE FOR ANY SPECIAL, INDIRECT OR
.\" CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
.\" DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
.\" TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.
.\"
.de TQ
.br
.ns
.TP \\$1
..
.TH XCM 3 "Version 0.4" "XFree86"

.SH NAME
Xcm \- X11 Colour Management functions
.SH SYNTAX
\&#include <X11/Xcm/Xcm.h> /* colour region handling */

\&#include <X11/Xcm/XcmDDC.h> /* CM EDID over i2c fetching */

\&#include <X11/Xcm/XcmEvents.h> /* CM event observation */

\&#include <X11/Xcm/XcmEdidParse.h.h> /* EDID parsing */
.nf    
.SH DESCRIPTION
.B Xcm
is a simple library designed to support window color region handling, ICC 
profile handling, EDID parsing and colour management event observation. 
The detailed description for region handling is covered in the net-color-spec. 
.SH RESTRICTIONS
.B Xcm
will remain upward compatible after a 1.0 release.
.SH AUTHORS
Tomas Carnecky for the net-color part, at time member of the OpenICC Project,
Kai-Uwe Behrmann, member of the OpenICC and Oyranos Projects.
.SH "SEE ALSO"
Xcm(3) XcolorProfile(3) XcolorRegion(3) XcmDDC(3) XcmEdidParse(3) XcmEvents(3)

