.TH "XcolorProfile" 3 "Mon May 11 2015" "Version 0.5.4" "Xcm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XcolorProfile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Xcm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBmd5\fP [16]"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBXcolorProfile\fP typedefed structure describes a single ICC profile\&. The 'md5' field is used to identify the profile\&. The actual data follows right after the structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t XcolorProfile::length"
number of bytes following, network byte order 
.PP
Referenced by XcolorProfileDelete(), and XcolorProfileUpload()\&.
.SS "uint8_t XcolorProfile::md5[16]"
ICC MD5 of the profile 

.SH "Author"
.PP 
Generated automatically by Doxygen for Xcm from the source code\&.
