.TH "XcolorProfile" 3 "6 Oct 2010" "Version 0.3.0" "Xcm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XcolorProfile \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Xcm.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBmd5\fP [16]"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBXcolorProfile\fP typedefed structure describes a single ICC profile. The 'md5' field is used to identify the profile. The actual data follows right after the structure. 
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBXcolorProfile::length\fP"
.PP
number of bytes following, network byte order 
.SS "uint8_t \fBXcolorProfile::md5\fP[16]"
.PP
ICC MD5 of the profile 

.SH "Author"
.PP 
Generated automatically by Doxygen for Xcm from the source code.
